name: synology

services:
  serveo:
    image: taichunmin/serveo:latest
    container_name: serveo
    tty: true
    stdin_open: true
    volumes:
      - .ssh:/root/.ssh
    command: >
      autossh -M 0
      -o ServerAliveInterval=60
      -o ServerAliveCountMax=3
      -o ExitOnForwardFailure=yes
      -o StrictHostKeyChecking=no
      -R $SUBDOMAIN:80:nginx:80
      $DOMAIN
  nginx:
    image: nginx:latest
    container_name: nginx
