name: synology

services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    restart: unless-stopped
    volumes:
      - ./config/sing-box:/etc/sing-box/
    ports:
      - 2080:2080
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./config/qbittorrent:/config
      - ./data:/data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    depends_on:
      - sing-box
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - HTTP_PROXY=http://sing-box:2080
      - HTTPS_PROXY=http://sing-box:2080
    env_file:
      - ./.env
    volumes:
      - ./config/jellyfin:/config
      - ./data:/data
    ports:
      - 8096:8096
    depends_on:
      - sing-box

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./config/radarr:/config
      - ./data:/data
    ports:
      - 7878:7878
    depends_on:
      - sing-box
      - qbittorrent
      - jellyfin
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./config/sonarr:/config
      - ./data:/data
    ports:
      - 8989:8989
    depends_on:
      - sing-box
      - qbittorrent
      - jellyfin
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    depends_on:
      - sing-box
      - qbittorrent
      - radarr
      - sonarr

  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    environment:
      - HTTP_PROXY=http://sing-box:2080
      - HTTPS_PROXY=http://sing-box:2080
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./config/coredns/Corefile:/Corefile
    depends_on:
      - sing-box
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    env_file:
      - ./.env
    dns:
      - coredns
    ports:
      - 5055:5055
    volumes:
      - ./config/jellyseerr:/app/config
    depends_on:
      - sing-box
      - radarr
      - sonarr
      - jellyfin
