#!/bin/bash

set -e

case "${radarr_eventtype}" in

  "Grab")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_Movie_Id - ${radarr_movie_id}"
    echo "Radarr_Movie_Title - ${radarr_movie_title}"
    echo "Radarr_Movie_Year - ${radarr_movie_year}"
    echo "Radarr_Movie_OriginalLanguage - ${radarr_movie_originallanguage}"
    echo "Radarr_Movie_Genres - ${radarr_movie_genres}"
    echo "Radarr_Movie_Tags - ${radarr_movie_tags}"
    echo "Radarr_Movie_ImdbId - ${radarr_movie_imdbid}"
    echo "Radarr_Movie_TmdbId - ${radarr_movie_tmdbid}"
    echo "Radarr_Movie_In_Cinemas_Date - ${radarr_movie_in_cinemas_date}"
    echo "Radarr_Movie_Physical_Release_Date - ${radarr_movie_physical_release_date}"
    echo "Radarr_Movie_Overview - ${radarr_movie_overview}"
    echo "Radarr_Release_Title - ${radarr_release_title}"
    echo "Radarr_Release_Indexer - ${radarr_release_indexer}"
    echo "Radarr_Release_Size - ${radarr_release_size}"
    echo "Radarr_Release_ReleaseGroup - ${radarr_release_releasegroup}"
    echo "Radarr_Release_Quality - ${radarr_release_quality}"
    echo "Radarr_Release_QualityVersion - ${radarr_release_qualityversion}"
    echo "Radarr_IndexerFlags - ${radarr_indexerflags}"
    echo "Radarr_Download_Client - ${radarr_download_client}"
    echo "Radarr_Download_Client_Type - ${radarr_download_client_type}"
    echo "Radarr_Download_Id - ${radarr_download_id}"
    echo "Radarr_Release_CustomFormat - ${radarr_release_customformat}"
    echo "Radarr_Release_CustomFormatScore - ${radarr_release_customformatscore}"
    ;;

  "Download")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_IsUpgrade - ${radarr_isupgrade}"
    echo "Radarr_Movie_Id - ${radarr_movie_id}"
    echo "Radarr_Movie_Title - ${radarr_movie_title}"
    echo "Radarr_Movie_Year - ${radarr_movie_year}"
    echo "Radarr_Movie_OriginalLanguage - ${radarr_movie_originallanguage}"
    echo "Radarr_Movie_Genres - ${radarr_movie_genres}"
    echo "Radarr_Movie_Tags - ${radarr_movie_tags}"
    echo "Radarr_Movie_Path - ${radarr_movie_path}"
    echo "Radarr_Movie_ImdbId - ${radarr_movie_imdbid}"
    echo "Radarr_Movie_TmdbId - ${radarr_movie_tmdbid}"
    echo "Radarr_Movie_In_Cinemas_Date - ${radarr_movie_in_cinemas_date}"
    echo "Radarr_Movie_Physical_Release_Date - ${radarr_movie_physical_release_date}"
    echo "Radarr_Movie_Overview - ${radarr_movie_overview}"
    echo "Radarr_MovieFile_Id - ${radarr_moviefile_id}"
    echo "Radarr_MovieFile_RelativePath - ${radarr_moviefile_relativepath}"
    echo "Radarr_MovieFile_Path - ${radarr_moviefile_path}"
    echo "Radarr_MovieFile_Quality - ${radarr_moviefile_quality}"
    echo "Radarr_MovieFile_QualityVersion - ${radarr_moviefile_qualityversion}"
    echo "Radarr_MovieFile_ReleaseGroup - ${radarr_moviefile_releasegroup}"
    echo "Radarr_MovieFile_SceneName - ${radarr_moviefile_scenename}"
    echo "Radarr_MovieFile_SourcePath - ${radarr_moviefile_sourcepath}"
    echo "Radarr_MovieFile_SourceFolder - ${radarr_moviefile_sourcefolder}"
    echo "Radarr_Download_Client - ${radarr_download_client}"
    echo "Radarr_Download_Client_Type - ${radarr_download_client_type}"
    echo "Radarr_Download_Id - ${radarr_download_id}"
    echo "Radarr_MovieFile_MediaInfo_AudioChannels - ${radarr_moviefile_mediainfo_audiochannels}"
    echo "Radarr_MovieFile_MediaInfo_AudioCodec - ${radarr_moviefile_mediainfo_audiocodec}"
    echo "Radarr_MovieFile_MediaInfo_AudioLanguages - ${radarr_moviefile_mediainfo_audiolanguages}"
    echo "Radarr_MovieFile_MediaInfo_Languages - ${radarr_moviefile_mediainfo_languages}"
    echo "Radarr_MovieFile_MediaInfo_Height - ${radarr_moviefile_mediainfo_height}"
    echo "Radarr_MovieFile_MediaInfo_Width - ${radarr_moviefile_mediainfo_width}"
    echo "Radarr_MovieFile_MediaInfo_Subtitles - ${radarr_moviefile_mediainfo_subtitles}"
    echo "Radarr_MovieFile_MediaInfo_VideoCodec - ${radarr_moviefile_mediainfo_videocodec}"
    echo "Radarr_MovieFile_MediaInfo_VideoDynamicRangeType - ${radarr_moviefile_mediainfo_videodynamicrangetype}"
    echo "Radarr_MovieFile_CustomFormat - ${radarr_moviefile_customformat}"
    echo "Radarr_MovieFile_CustomFormatScore - ${radarr_moviefile_customformatscore}"
    echo "Radarr_Release_Indexer - ${radarr_release_indexer}"
    echo "Radarr_Release_Size - ${radarr_release_size}"
    echo "Radarr_Release_Title - ${radarr_release_title}"
    echo "Radarr_DeletedRelativePaths - ${radarr_deletedrelativepaths}"
    echo "Radarr_DeletedPaths - ${radarr_deletedpaths}"
    echo "Radarr_DeletedDateAdded - ${radarr_deleteddateadded}"
    echo "Radarr_DeletedRecycleBinPaths - ${radarr_deletedrecyclebinpaths}"
    ;;

  "Rename")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_Movie_Id - ${radarr_movie_id}"
    echo "Radarr_Movie_Title - ${radarr_movie_title}"
    echo "Radarr_Movie_Year - ${radarr_movie_year}"
    echo "Radarr_Movie_OriginalLanguage - ${radarr_movie_originallanguage}"
    echo "Radarr_Movie_Genres - ${radarr_movie_genres}"
    echo "Radarr_Movie_Tags - ${radarr_movie_tags}"
    echo "Radarr_Movie_Path - ${radarr_movie_path}"
    echo "Radarr_Movie_ImdbId - ${radarr_movie_imdbid}"
    echo "Radarr_Movie_TmdbId - ${radarr_movie_tmdbid}"
    echo "Radarr_Movie_In_Cinemas_Date - ${radarr_movie_in_cinemas_date}"
    echo "Radarr_Movie_Physical_Release_Date - ${radarr_movie_physical_release_date}"
    echo "Radarr_MovieFile_Ids - ${radarr_moviefile_ids}"
    echo "Radarr_MovieFile_RelativePaths - ${radarr_moviefile_relativepaths}"
    echo "Radarr_MovieFile_Paths - ${radarr_moviefile_paths}"
    echo "Radarr_MovieFile_PreviousRelativePaths - ${radarr_moviefile_previousrelativepaths}"
    echo "Radarr_MovieFile_PreviousPaths - ${radarr_moviefile_previouspaths}"
    ;;

  "MovieAdded")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_Movie_Id - ${radarr_movie_id}"
    echo "Radarr_Movie_Title - ${radarr_movie_title}"
    echo "Radarr_Movie_Year - ${radarr_movie_year}"
    echo "Radarr_Movie_OriginalLanguage - ${radarr_movie_originallanguage}"
    echo "Radarr_Movie_Genres - ${radarr_movie_genres}"
    echo "Radarr_Movie_Tags - ${radarr_movie_tags}"
    echo "Radarr_Movie_Path - ${radarr_movie_path}"
    echo "Radarr_Movie_ImdbId - ${radarr_movie_imdbid}"
    echo "Radarr_Movie_TmdbId - ${radarr_movie_tmdbid}"
    echo "Radarr_Movie_AddMethod - ${radarr_movie_addmethod}"
    ;;

  "MovieFileDelete")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_MovieFile_DeleteReason - ${radarr_moviefile_deletereason}"
    echo "Radarr_Movie_Id - ${radarr_movie_id}"
    echo "Radarr_Movie_Title - ${radarr_movie_title}"
    echo "Radarr_Movie_Year - ${radarr_movie_year}"
    echo "Radarr_Movie_OriginalLanguage - ${radarr_movie_originallanguage}"
    echo "Radarr_Movie_Genres - ${radarr_movie_genres}"
    echo "Radarr_Movie_Tags - ${radarr_movie_tags}"
    echo "Radarr_Movie_Path - ${radarr_movie_path}"
    echo "Radarr_Movie_ImdbId - ${radarr_movie_imdbid}"
    echo "Radarr_Movie_TmdbId - ${radarr_movie_tmdbid}"
    echo "Radarr_Movie_Overview - ${radarr_movie_overview}"
    echo "Radarr_MovieFile_Id - ${radarr_moviefile_id}"
    echo "Radarr_MovieFile_RelativePath - ${radarr_moviefile_relativepath}"
    echo "Radarr_MovieFile_Path - ${radarr_moviefile_path}"
    echo "Radarr_MovieFile_Size - ${radarr_moviefile_size}"
    echo "Radarr_MovieFile_Quality - ${radarr_moviefile_quality}"
    echo "Radarr_MovieFile_QualityVersion - ${radarr_moviefile_qualityversion}"
    echo "Radarr_MovieFile_ReleaseGroup - ${radarr_moviefile_releasegroup}"
    echo "Radarr_MovieFile_SceneName - ${radarr_moviefile_scenename}"
    ;;

  "MovieDelete")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_Movie_Id - ${radarr_movie_id}"
    echo "Radarr_Movie_Title - ${radarr_movie_title}"
    echo "Radarr_Movie_Year - ${radarr_movie_year}"
    echo "Radarr_Movie_OriginalLanguage - ${radarr_movie_originallanguage}"
    echo "Radarr_Movie_Genres - ${radarr_movie_genres}"
    echo "Radarr_Movie_Tags - ${radarr_movie_tags}"
    echo "Radarr_Movie_Path - ${radarr_movie_path}"
    echo "Radarr_Movie_ImdbId - ${radarr_movie_imdbid}"
    echo "Radarr_Movie_TmdbId - ${radarr_movie_tmdbid}"
    echo "Radarr_Movie_DeletedFiles - ${radarr_movie_deletedfiles}"
    echo "Radarr_Movie_Overview - ${radarr_movie_overview}"
    echo "Radarr_Movie_Folder_Size - ${radarr_movie_folder_size}"
    ;;

  "HealthIssue")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_Health_Issue_Level - ${radarr_health_issue_level}"
    echo "Radarr_Health_Issue_Message - ${radarr_health_issue_message}"
    echo "Radarr_Health_Issue_Type - ${radarr_health_issue_type}"
    echo "Radarr_Health_Issue_Wiki - ${radarr_health_issue_wiki}"
    ;;

  "HealthRestored")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_Health_Restored_Level - ${radarr_health_restored_level}"
    echo "Radarr_Health_Restored_Message - ${radarr_health_restored_message}"
    echo "Radarr_Health_Restored_Type - ${radarr_health_restored_type}"
    echo "Radarr_Health_Restored_Wiki - ${radarr_health_restored_wiki}"
    ;;

  "ApplicationUpdate")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_Update_Message - ${radarr_update_message}"
    echo "Radarr_Update_NewVersion - ${radarr_update_newversion}"
    echo "Radarr_Update_PreviousVersion - ${radarr_update_previousversion}"
    ;;

  "ManualInteractionRequired")
    echo "Radarr_EventType - ${radarr_eventtype}"
    echo "Radarr_InstanceName - ${radarr_instancename}"
    echo "Radarr_ApplicationUrl - ${radarr_applicationurl}"
    echo "Radarr_Movie_Id - ${radarr_movie_id}"
    echo "Radarr_Movie_Title - ${radarr_movie_title}"
    echo "Radarr_Movie_Year - ${radarr_movie_year}"
    echo "Radarr_Movie_OriginalLanguage - ${radarr_movie_originallanguage}"
    echo "Radarr_Movie_Genres - ${radarr_movie_genres}"
    echo "Radarr_Movie_Tags - ${radarr_movie_tags}"
    echo "Radarr_Movie_Path - ${radarr_movie_path}"
    echo "Radarr_Movie_ImdbId - ${radarr_movie_imdbid}"
    echo "Radarr_Movie_TmdbId - ${radarr_movie_tmdbid}"
    echo "Radarr_Movie_Overview - ${radarr_movie_overview}"
    echo "Radarr_Download_Client - ${radarr_download_client}"
    echo "Radarr_Download_Client_Type - ${radarr_download_client_type}"
    echo "Radarr_Download_Id - ${radarr_download_id}"
    echo "Radarr_Download_Size - ${radarr_download_size}"
    echo "Radarr_Download_Title - ${radarr_download_title}"
    ;;
esac
