#!/bin/bash

set -e

case "${Sonarr_EventType}" in

  "Grab")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_Series_Id - '${Sonarr_Series_Id}'"
    echo "Sonarr_Series_Title - '${Sonarr_Series_Title}'"
    echo "Sonarr_Series_TitleSlug - '${Sonarr_Series_TitleSlug}'"
    echo "Sonarr_Series_TvdbId - '${Sonarr_Series_TvdbId}'"
    echo "Sonarr_Series_TvMazeId - '${Sonarr_Series_TvMazeId}'"
    echo "Sonarr_Series_TmdbId - '${Sonarr_Series_TmdbId}'"
    echo "Sonarr_Series_ImdbId - '${Sonarr_Series_ImdbId}'"
    echo "Sonarr_Series_Type - '${Sonarr_Series_Type}'"
    echo "Sonarr_Series_Year - '${Sonarr_Series_Year}'"
    echo "Sonarr_Series_OriginalLanguage - '${Sonarr_Series_OriginalLanguage}'"
    echo "Sonarr_Series_Genres - '${Sonarr_Series_Genres}'"
    echo "Sonarr_Series_Tags - '${Sonarr_Series_Tags}'"
    echo "Sonarr_Release_EpisodeCount - '${Sonarr_Release_EpisodeCount}'"
    echo "Sonarr_Release_SeasonNumber - '${Sonarr_Release_SeasonNumber}'"
    echo "Sonarr_Release_EpisodeNumbers - '${Sonarr_Release_EpisodeNumbers}'"
    echo "Sonarr_Release_AbsoluteEpisodeNumbers - '${Sonarr_Release_AbsoluteEpisodeNumbers}'"
    echo "Sonarr_Release_EpisodeAirDates - '${Sonarr_Release_EpisodeAirDates}'"
    echo "Sonarr_Release_EpisodeAirDatesUtc - '${Sonarr_Release_EpisodeAirDatesUtc}'"
    echo "Sonarr_Release_EpisodeTitles - '${Sonarr_Release_EpisodeTitles}'"
    echo "Sonarr_Release_EpisodeOverviews - '${Sonarr_Release_EpisodeOverviews}'"
    echo "Sonarr_Release_Title - '${Sonarr_Release_Title}'"
    echo "Sonarr_Release_Indexer - '${Sonarr_Release_Indexer}'"
    echo "Sonarr_Release_Size - '${Sonarr_Release_Size}'"
    echo "Sonarr_Release_Quality - '${Sonarr_Release_Quality}'"
    echo "Sonarr_Release_QualityVersion - '${Sonarr_Release_QualityVersion}'"
    echo "Sonarr_Release_ReleaseGroup - '${Sonarr_Release_ReleaseGroup}'"
    echo "Sonarr_Release_IndexerFlags - '${Sonarr_Release_IndexerFlags}'"
    echo "Sonarr_Download_Client - '${Sonarr_Download_Client}'"
    echo "Sonarr_Download_Client_Type - '${Sonarr_Download_Client_Type}'"
    echo "Sonarr_Download_Id - '${Sonarr_Download_Id}'"
    echo "Sonarr_Release_CustomFormat - '${Sonarr_Release_CustomFormat}'"
    echo "Sonarr_Release_CustomFormatScore - '${Sonarr_Release_CustomFormatScore}'"
    echo "Sonarr_Release_ReleaseType - '${Sonarr_Release_ReleaseType}'"
    ;;

  "Download")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_IsUpgrade - '${Sonarr_IsUpgrade}'"
    echo "Sonarr_Series_Id - '${Sonarr_Series_Id}'"
    echo "Sonarr_Series_Title - '${Sonarr_Series_Title}'"
    echo "Sonarr_Series_TitleSlug - '${Sonarr_Series_TitleSlug}'"
    echo "Sonarr_Series_Path - '${Sonarr_Series_Path}'"
    echo "Sonarr_Series_TvdbId - '${Sonarr_Series_TvdbId}'"
    echo "Sonarr_Series_TvMazeId - '${Sonarr_Series_TvMazeId}'"
    echo "Sonarr_Series_TmdbId - '${Sonarr_Series_TmdbId}'"
    echo "Sonarr_Series_ImdbId - '${Sonarr_Series_ImdbId}'"
    echo "Sonarr_Series_Type - '${Sonarr_Series_Type}'"
    echo "Sonarr_Series_Year - '${Sonarr_Series_Year}'"
    echo "Sonarr_Series_OriginalLanguage - '${Sonarr_Series_OriginalLanguage}'"
    echo "Sonarr_Series_Genres - '${Sonarr_Series_Genres}'"
    echo "Sonarr_Series_Tags - '${Sonarr_Series_Tags}'"
    echo "Sonarr_EpisodeFile_Id - '${Sonarr_EpisodeFile_Id}'"
    echo "Sonarr_EpisodeFile_EpisodeCount - '${Sonarr_EpisodeFile_EpisodeCount}'"
    echo "Sonarr_EpisodeFile_RelativePath - '${Sonarr_EpisodeFile_RelativePath}'"
    echo "Sonarr_EpisodeFile_Path - '${Sonarr_EpisodeFile_Path}'"
    echo "Sonarr_EpisodeFile_EpisodeIds - '${Sonarr_EpisodeFile_EpisodeIds}'"
    echo "Sonarr_EpisodeFile_SeasonNumber - '${Sonarr_EpisodeFile_SeasonNumber}'"
    echo "Sonarr_EpisodeFile_EpisodeNumbers - '${Sonarr_EpisodeFile_EpisodeNumbers}'"
    echo "Sonarr_EpisodeFile_EpisodeAirDates - '${Sonarr_EpisodeFile_EpisodeAirDates}'"
    echo "Sonarr_EpisodeFile_EpisodeAirDatesUtc - '${Sonarr_EpisodeFile_EpisodeAirDatesUtc}'"
    echo "Sonarr_EpisodeFile_EpisodeTitles - '${Sonarr_EpisodeFile_EpisodeTitles}'"
    echo "Sonarr_EpisodeFile_EpisodeOverviews - '${Sonarr_EpisodeFile_EpisodeOverviews}'"
    echo "Sonarr_EpisodeFile_Quality - '${Sonarr_EpisodeFile_Quality}'"
    echo "Sonarr_EpisodeFile_QualityVersion - '${Sonarr_EpisodeFile_QualityVersion}'"
    echo "Sonarr_EpisodeFile_ReleaseGroup - '${Sonarr_EpisodeFile_ReleaseGroup}'"
    echo "Sonarr_EpisodeFile_SceneName - '${Sonarr_EpisodeFile_SceneName}'"
    echo "Sonarr_EpisodeFile_SourcePath - '${Sonarr_EpisodeFile_SourcePath}'"
    echo "Sonarr_EpisodeFile_SourceFolder - '${Sonarr_EpisodeFile_SourceFolder}'"
    echo "Sonarr_Download_Client - '${Sonarr_Download_Client}'"
    echo "Sonarr_Download_Client_Type - '${Sonarr_Download_Client_Type}'"
    echo "Sonarr_Download_Id - '${Sonarr_Download_Id}'"
    echo "Sonarr_EpisodeFile_MediaInfo_AudioChannels - '${Sonarr_EpisodeFile_MediaInfo_AudioChannels}'"
    echo "Sonarr_EpisodeFile_MediaInfo_AudioCodec - '${Sonarr_EpisodeFile_MediaInfo_AudioCodec}'"
    echo "Sonarr_EpisodeFile_MediaInfo_AudioLanguages - '${Sonarr_EpisodeFile_MediaInfo_AudioLanguages}'"
    echo "Sonarr_EpisodeFile_MediaInfo_Languages - '${Sonarr_EpisodeFile_MediaInfo_Languages}'"
    echo "Sonarr_EpisodeFile_MediaInfo_Height - '${Sonarr_EpisodeFile_MediaInfo_Height}'"
    echo "Sonarr_EpisodeFile_MediaInfo_Width - '${Sonarr_EpisodeFile_MediaInfo_Width}'"
    echo "Sonarr_EpisodeFile_MediaInfo_Subtitles - '${Sonarr_EpisodeFile_MediaInfo_Subtitles}'"
    echo "Sonarr_EpisodeFile_MediaInfo_VideoCodec - '${Sonarr_EpisodeFile_MediaInfo_VideoCodec}'"
    echo "Sonarr_EpisodeFile_MediaInfo_VideoDynamicRangeType - '${Sonarr_EpisodeFile_MediaInfo_VideoDynamicRangeType}'"
    echo "Sonarr_EpisodeFile_CustomFormat - '${Sonarr_EpisodeFile_CustomFormat}'"
    echo "Sonarr_EpisodeFile_CustomFormatScore - '${Sonarr_EpisodeFile_CustomFormatScore}'"
    echo "Sonarr_Release_Indexer - '${Sonarr_Release_Indexer}'"
    echo "Sonarr_Release_Size - '${Sonarr_Release_Size}'"
    echo "Sonarr_Release_Title - '${Sonarr_Release_Title}'"
    echo "Sonarr_Release_ReleaseType - '${Sonarr_Release_ReleaseType}'"

    echo "Sonarr_DeletedRelativePaths - '${Sonarr_DeletedRelativePaths}'"
    echo "Sonarr_DeletedPaths - '${Sonarr_DeletedPaths}'"
    echo "Sonarr_DeletedDateAdded - '${Sonarr_DeletedDateAdded}'"
    echo "Sonarr_DeletedRecycleBinPaths - '${Sonarr_DeletedRecycleBinPaths}'"
#     ;;
#
#   "Download")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_Series_Id - '${Sonarr_Series_Id}'"
    echo "Sonarr_Series_Title - '${Sonarr_Series_Title}'"
    echo "Sonarr_Series_TitleSlug - '${Sonarr_Series_TitleSlug}'"
    echo "Sonarr_Series_Path - '${Sonarr_Series_Path}'"
    echo "Sonarr_Series_TvdbId - '${Sonarr_Series_TvdbId}'"
    echo "Sonarr_Series_TvMazeId - '${Sonarr_Series_TvMazeId}'"
    echo "Sonarr_Series_TmdbId - '${Sonarr_Series_TmdbId}'"
    echo "Sonarr_Series_ImdbId - '${Sonarr_Series_ImdbId}'"
    echo "Sonarr_Series_Type - '${Sonarr_Series_Type}'"
    echo "Sonarr_Series_Year - '${Sonarr_Series_Year}'"
    echo "Sonarr_Series_OriginalLanguage - '${Sonarr_Series_OriginalLanguage}'"
    echo "Sonarr_Series_Genres - '${Sonarr_Series_Genres}'"
    echo "Sonarr_Series_Tags - '${Sonarr_Series_Tags}'"
    echo "Sonarr_EpisodeFile_Ids - '${Sonarr_EpisodeFile_Ids}'"
    echo "Sonarr_EpisodeFile_Count - '${Sonarr_EpisodeFile_Count}'"
    echo "Sonarr_EpisodeFile_RelativePaths - '${Sonarr_EpisodeFile_RelativePaths}'"
    echo "Sonarr_EpisodeFile_Paths - '${Sonarr_EpisodeFile_Paths}'"
    echo "Sonarr_EpisodeFile_EpisodeIds - '${Sonarr_EpisodeFile_EpisodeIds}'"
    echo "Sonarr_EpisodeFile_SeasonNumber - '${Sonarr_EpisodeFile_SeasonNumber}'"
    echo "Sonarr_EpisodeFile_EpisodeNumbers - '${Sonarr_EpisodeFile_EpisodeNumbers}'"
    echo "Sonarr_EpisodeFile_EpisodeAirDates - '${Sonarr_EpisodeFile_EpisodeAirDates}'"
    echo "Sonarr_EpisodeFile_EpisodeAirDatesUtc - '${Sonarr_EpisodeFile_EpisodeAirDatesUtc}'"
    echo "Sonarr_EpisodeFile_EpisodeTitles - '${Sonarr_EpisodeFile_EpisodeTitles}'"
    echo "Sonarr_EpisodeFile_EpisodeOverviews - '${Sonarr_EpisodeFile_EpisodeOverviews}'"
    echo "Sonarr_EpisodeFile_Qualities - '${Sonarr_EpisodeFile_Qualities}'"
    echo "Sonarr_EpisodeFile_QualityVersions - '${Sonarr_EpisodeFile_QualityVersions}'"
    echo "Sonarr_EpisodeFile_ReleaseGroups - '${Sonarr_EpisodeFile_ReleaseGroups}'"
    echo "Sonarr_EpisodeFile_SceneNames - '${Sonarr_EpisodeFile_SceneNames}'"
    echo "Sonarr_Download_Client - '${Sonarr_Download_Client}'"
    echo "Sonarr_Download_Client_Type - '${Sonarr_Download_Client_Type}'"
    echo "Sonarr_Download_Id - '${Sonarr_Download_Id}'"
    echo "Sonarr_Release_Group - '${Sonarr_Release_Group}'"
    echo "Sonarr_Release_Quality - '${Sonarr_Release_Quality}'"
    echo "Sonarr_Release_QualityVersion - '${Sonarr_Release_QualityVersion}'"
    echo "Sonarr_Release_Indexer - '${Sonarr_Release_Indexer}'"
    echo "Sonarr_Release_Size - '${Sonarr_Release_Size}'"
    echo "Sonarr_Release_Title - '${Sonarr_Release_Title}'"

    echo "Sonarr_Release_ReleaseType - '${Sonarr_Release_ReleaseType}'"
    echo "Sonarr_SourcePath - '${Sonarr_SourcePath}'"
    echo "Sonarr_SourceFolder - '${Sonarr_SourceFolder}'"
    echo "Sonarr_DestinationPath - '${Sonarr_DestinationPath}'"
    echo "Sonarr_DestinationFolder - '${Sonarr_DestinationFolder}'"
    ;;

  "Rename")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_Series_Id - '${Sonarr_Series_Id}'"
    echo "Sonarr_Series_Title - '${Sonarr_Series_Title}'"
    echo "Sonarr_Series_TitleSlug - '${Sonarr_Series_TitleSlug}'"
    echo "Sonarr_Series_Path - '${Sonarr_Series_Path}'"
    echo "Sonarr_Series_TvdbId - '${Sonarr_Series_TvdbId}'"
    echo "Sonarr_Series_TvMazeId - '${Sonarr_Series_TvMazeId}'"
    echo "Sonarr_Series_TmdbId - '${Sonarr_Series_TmdbId}'"
    echo "Sonarr_Series_ImdbId - '${Sonarr_Series_ImdbId}'"
    echo "Sonarr_Series_Type - '${Sonarr_Series_Type}'"
    echo "Sonarr_Series_Year - '${Sonarr_Series_Year}'"
    echo "Sonarr_Series_OriginalLanguage - '${Sonarr_Series_OriginalLanguage}'"
    echo "Sonarr_Series_Genres - '${Sonarr_Series_Genres}'"
    echo "Sonarr_Series_Tags - '${Sonarr_Series_Tags}'"
    echo "Sonarr_EpisodeFile_Ids - '${Sonarr_EpisodeFile_Ids}'"
    echo "Sonarr_EpisodeFile_RelativePaths - '${Sonarr_EpisodeFile_RelativePaths}'"
    echo "Sonarr_EpisodeFile_Paths - '${Sonarr_EpisodeFile_Paths}'"
    echo "Sonarr_EpisodeFile_PreviousRelativePaths - '${Sonarr_EpisodeFile_PreviousRelativePaths}'"
    echo "Sonarr_EpisodeFile_PreviousPaths - '${Sonarr_EpisodeFile_PreviousPaths}'"
    ;;

  "EpisodeFileDelete")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_EpisodeFile_DeleteReason - '${Sonarr_EpisodeFile_DeleteReason}'"
    echo "Sonarr_Series_Id - '${Sonarr_Series_Id}'"
    echo "Sonarr_Series_Title - '${Sonarr_Series_Title}'"
    echo "Sonarr_Series_TitleSlug - '${Sonarr_Series_TitleSlug}'"
    echo "Sonarr_Series_Path - '${Sonarr_Series_Path}'"
    echo "Sonarr_Series_TvdbId - '${Sonarr_Series_TvdbId}'"
    echo "Sonarr_Series_TvMazeId - '${Sonarr_Series_TvMazeId}'"
    echo "Sonarr_Series_TmdbId - '${Sonarr_Series_TmdbId}'"
    echo "Sonarr_Series_ImdbId - '${Sonarr_Series_ImdbId}'"
    echo "Sonarr_Series_Type - '${Sonarr_Series_Type}'"
    echo "Sonarr_Series_Year - '${Sonarr_Series_Year}'"
    echo "Sonarr_Series_OriginalLanguage - '${Sonarr_Series_OriginalLanguage}'"
    echo "Sonarr_Series_Genres - '${Sonarr_Series_Genres}'"
    echo "Sonarr_Series_Tags - '${Sonarr_Series_Tags}'"
    echo "Sonarr_EpisodeFile_Id - '${Sonarr_EpisodeFile_Id}'"
    echo "Sonarr_EpisodeFile_EpisodeCount - '${Sonarr_EpisodeFile_EpisodeCount}'"
    echo "Sonarr_EpisodeFile_RelativePath - '${Sonarr_EpisodeFile_RelativePath}'"
    echo "Sonarr_EpisodeFile_Path - '${Sonarr_EpisodeFile_Path}'"
    echo "Sonarr_EpisodeFile_EpisodeIds - '${Sonarr_EpisodeFile_EpisodeIds}'"
    echo "Sonarr_EpisodeFile_SeasonNumber - '${Sonarr_EpisodeFile_SeasonNumber}'"
    echo "Sonarr_EpisodeFile_EpisodeNumbers - '${Sonarr_EpisodeFile_EpisodeNumbers}'"
    echo "Sonarr_EpisodeFile_EpisodeAirDates - '${Sonarr_EpisodeFile_EpisodeAirDates}'"
    echo "Sonarr_EpisodeFile_EpisodeAirDatesUtc - '${Sonarr_EpisodeFile_EpisodeAirDatesUtc}'"
    echo "Sonarr_EpisodeFile_EpisodeTitles - '${Sonarr_EpisodeFile_EpisodeTitles}'"
    echo "Sonarr_EpisodeFile_EpisodeOverviews - '${Sonarr_EpisodeFile_EpisodeOverviews}'"
    echo "Sonarr_EpisodeFile_Quality - '${Sonarr_EpisodeFile_Quality}'"
    echo "Sonarr_EpisodeFile_QualityVersion - '${Sonarr_EpisodeFile_QualityVersion}'"
    echo "Sonarr_EpisodeFile_ReleaseGroup - '${Sonarr_EpisodeFile_ReleaseGroup}'"
    echo "Sonarr_EpisodeFile_SceneName - '${Sonarr_EpisodeFile_SceneName}'"
    ;;

  "SeriesAdd")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_Series_Id - '${Sonarr_Series_Id}'"
    echo "Sonarr_Series_Title - '${Sonarr_Series_Title}'"
    echo "Sonarr_Series_TitleSlug - '${Sonarr_Series_TitleSlug}'"
    echo "Sonarr_Series_Path - '${Sonarr_Series_Path}'"
    echo "Sonarr_Series_TvdbId - '${Sonarr_Series_TvdbId}'"
    echo "Sonarr_Series_TvMazeId - '${Sonarr_Series_TvMazeId}'"
    echo "Sonarr_Series_TmdbId - '${Sonarr_Series_TmdbId}'"
    echo "Sonarr_Series_ImdbId - '${Sonarr_Series_ImdbId}'"
    echo "Sonarr_Series_Type - '${Sonarr_Series_Type}'"
    echo "Sonarr_Series_Year - '${Sonarr_Series_Year}'"
    echo "Sonarr_Series_OriginalLanguage - '${Sonarr_Series_OriginalLanguage}'"
    echo "Sonarr_Series_Genres - '${Sonarr_Series_Genres}'"
    echo "Sonarr_Series_Tags - '${Sonarr_Series_Tags}'"
    ;;

  "SeriesDelete")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_Series_Id - '${Sonarr_Series_Id}'"
    echo "Sonarr_Series_Title - '${Sonarr_Series_Title}'"
    echo "Sonarr_Series_TitleSlug - '${Sonarr_Series_TitleSlug}'"
    echo "Sonarr_Series_Path - '${Sonarr_Series_Path}'"
    echo "Sonarr_Series_TvdbId - '${Sonarr_Series_TvdbId}'"
    echo "Sonarr_Series_TvMazeId - '${Sonarr_Series_TvMazeId}'"
    echo "Sonarr_Series_TmdbId - '${Sonarr_Series_TmdbId}'"
    echo "Sonarr_Series_ImdbId - '${Sonarr_Series_ImdbId}'"
    echo "Sonarr_Series_Type - '${Sonarr_Series_Type}'"
    echo "Sonarr_Series_Year - '${Sonarr_Series_Year}'"
    echo "Sonarr_Series_OriginalLanguage - '${Sonarr_Series_OriginalLanguage}'"
    echo "Sonarr_Series_Genres - '${Sonarr_Series_Genres}'"
    echo "Sonarr_Series_Tags - '${Sonarr_Series_Tags}'"
    echo "Sonarr_Series_DeletedFiles - '${Sonarr_Series_DeletedFiles}'"
    ;;

  "HealthIssue")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_Health_Issue_Level - '${Sonarr_Health_Issue_Level}'"
    echo "Sonarr_Health_Issue_Message - '${Sonarr_Health_Issue_Message}'"
    echo "Sonarr_Health_Issue_Type - '${Sonarr_Health_Issue_Type}'"
    echo "Sonarr_Health_Issue_Wiki - '${Sonarr_Health_Issue_Wiki}'"
    ;;

  "HealthRestored")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_Health_Restored_Level - '${Sonarr_Health_Restored_Level}'"
    echo "Sonarr_Health_Restored_Message - '${Sonarr_Health_Restored_Message}'"
    echo "Sonarr_Health_Restored_Type - '${Sonarr_Health_Restored_Type}'"
    echo "Sonarr_Health_Restored_Wiki - '${Sonarr_Health_Restored_Wiki}'"
    ;;

  "ApplicationUpdate")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_Update_Message - '${Sonarr_Update_Message}'"
    echo "Sonarr_Update_NewVersion - '${Sonarr_Update_NewVersion}'"
    echo "Sonarr_Update_PreviousVersion - '${Sonarr_Update_PreviousVersion}'"
    ;;

  "ManualInteractionRequired")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    echo "Sonarr_Series_Id - '${Sonarr_Series_Id}'"
    echo "Sonarr_Series_Title - '${Sonarr_Series_Title}'"
    echo "Sonarr_Series_TitleSlug - '${Sonarr_Series_TitleSlug}'"
    echo "Sonarr_Series_Path - '${Sonarr_Series_Path}'"
    echo "Sonarr_Series_TvdbId - '${Sonarr_Series_TvdbId}'"
    echo "Sonarr_Series_TvMazeId - '${Sonarr_Series_TvMazeId}'"
    echo "Sonarr_Series_TmdbId - '${Sonarr_Series_TmdbId}'"
    echo "Sonarr_Series_ImdbId - '${Sonarr_Series_ImdbId}'"
    echo "Sonarr_Series_Type - '${Sonarr_Series_Type}'"
    echo "Sonarr_Series_Year - '${Sonarr_Series_Year}'"
    echo "Sonarr_Series_OriginalLanguage - '${Sonarr_Series_OriginalLanguage}'"
    echo "Sonarr_Series_Genres - '${Sonarr_Series_Genres}'"
    echo "Sonarr_Series_Tags - '${Sonarr_Series_Tags}'"
    echo "Sonarr_Download_Client - '${Sonarr_Download_Client}'"
    echo "Sonarr_Download_Client_Type - '${Sonarr_Download_Client_Type}'"
    echo "Sonarr_Download_Id - '${Sonarr_Download_Id}'"
    echo "Sonarr_Download_Size - '${Sonarr_Download_Size}'"
    echo "Sonarr_Download_Title - '${Sonarr_Download_Title}'"
    ;;

  "Test")
    echo "Sonarr_EventType - '${Sonarr_EventType}'"
    echo "Sonarr_InstanceName - '${Sonarr_InstanceName}'"
    echo "Sonarr_ApplicationUrl - '${Sonarr_ApplicationUrl}'"
    ;;
esac
